### ISSUE TITLE
Loosen dependency requirements to allow for packaging

### ISSUE THREAD

**Issue by djmattyg007** [afroisalreadyinu/stashpy#1]
It would be nice if the dependencies in requirements.txt were loosened to not depend on exact versions. This would make it easier to package for Linux distributions, so that it can work with the version of a particular dependency in the system's package.

I understand that it's not the responsibility of developers to support every combination of dependency versions and development environments, so I'm saying this only with "up to date" distributions like Arch Linux in mind.

**Comment by afroisalreadyinu** [comment]
There are two kinds of dependency specifications here: setup.py and requirements.txt. The second is for repeatable builds, which [circumvents the fact that pip does not do proper dependency resolution](http://pip-python3.readthedocs.org/en/latest/user_guide.html#requirements-files). The dependencies in setup.py, on the other hand, can be soft. In my experience, keeping this separation is a good idea, because when you check out a project, you can simply run `pip install -r requirements.txt` and be sure that it will work, but when you're developing it and want to install a new dependency, you can run `python setup.py develop`, and fix any issues yourself.

So, my proposal would be to make the dependencies in setup.py more precise, but keep them soft. Would that make sense?

**Comment by djmattyg007** [comment]
It does make sense. To confirm, when you say making the dependencies more precise, you mean adding the dependencies that are in requirements.txt that aren't currently in setup.py?

**Comment by afroisalreadyinu** [comment]
Yes, exactly. So for example the nose2 dependency would become `nose2==0.6.*`.

**Comment by afroisalreadyinu** [comment]
https://github.com/afroisalreadyinu/stashpy/commit/61d2d019f43b61d1468634d2d0bf0bf2861263c8
